version: "3"
services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80" # 호스트의 80번 포트를 Nginx 80번과 매핑
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - app-network

networks:
  app-network:
    external: true
