version: '3.8'

services:
  green:
    image: yoonhyojin1016/kurlykelly_server:latest
    container_name: green
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=blue
    ports:
      - "8082:8080"
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: mysql-green
    env_file:
      - .env
    volumes:
      - mysql-green-data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-green-data:
