version: "3"

services:
  blue:
    image: yoonhyojin1016/kurlykelly_server:latest
    # image: ${DOCKERHUB_USERNAME}/kurlykelly_server:latest
    container_name: blue
    environment:
      - SPRING_PROFILES_ACTIVE=blue
      - MYSQL_URL=${MYSQL_URL}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

    ports:
      - "8081:8081"
    restart: always
