spring:
  profiles: blue
  datasource:
    # 프로덕션 DB 연결 정보 (환경변수로 주입)
    url: ${MYSQL_URL_PROD}
    username: ${MYSQL_USER_PROD}
    password: ${MYSQL_PASSWORD_PROD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      # EC2(리눅스) 서버의 파일 업로드 경로
      location: /var/upload

server:
  port: 8081 # Blue 인스턴스 전용 포트

logging:
  level:
    root: INFO
