spring:
  config:
    activate:
      on-profile: blue
  data:
    redis:
      host: kurlykelly-cache-server.gaatel.ng.0001.apn2.cache.amazonaws.com
      port: 6379

  datasource:
    # 프로덕션 DB 연결 정보 (환경변수로 주입)
    url: ${MYSQL_URL}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      # EC2(리눅스) 서버의 파일 업로드 경로
      location: /var/upload

server:
  port: 8081 # Blue 인스턴스 전용 포트

logging:
  level:
    root: INFO
