spring:
  profiles: dev

server:
  port: 8080

logging:
  level:
    root: DEBUG

  datasource:
    # 기본 개발용 DB (dev 환경) : .env 또는 환경변수로 주입되는 값 사용
    url: ${MYSQL_URL}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
